#+title: Tehnici Avansate de Programare
#+author: Petru Rebeja
#+description: Pagina cursului Technici Avansate de Programare. Facultatea de Matematică, Universitatea Alexandru Ioan Cuza, Iași.
#+language: ro
#+select_tags: export
#+startup: content
#+exclude_tags: noexport
#+options: author:t broken-links:nil c:nil creator:nil
#+options: timestamp:nil title:t toc:t todo:t |:t
#+options: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+setupfile: theme-readtheorg.setup
#+html_mathjax: align: left indent: 5em tagside: left font: Neo-Euler
* Prezentare
  :PROPERTIES:
  :CUSTOM_ID: prezentare
  :END:
  Cursul *Tehnici Avansate de Programare* își propune să faciliteze să ofere pregătirea necesară pentru studenții Facultății de Matematică în vederea urmării unei cariere în domeniul IT.

  Pe parcursul cursului studenții vor acumula un set de bune practici pentru dezvoltarea produselor software pe care le vor aplica lucrând în echipe la dezvoltarea unei aplicații Web.
Aplicația va fi propusă de către membrii echipei.
* Fișa disciplinei
  :PROPERTIES:
  :CUSTOM_ID: fisa-disciplinei
  :END:
** Date despre program
   :PROPERTIES:
   :CUSTOM_ID: date-despre-program
   :END:
   | Instituția de învățământ        | Universitatea „Alexandru Ioan Cuza” din Iași |
   | Facultatea                      | Facultatea de Matematică                     |
   | Departamentul                   | Matematică                                   |
   | Domeniul de studii              | Matematică                                   |
   | Ciclul de studii                | Licență                                      |
   | Programul de studii/Calificarea | Matematică-Informatică                       |
** Date despre disciplină
   :PROPERTIES:
   :CUSTOM_ID: date-despre-disciplina
   :END:
   | Denumirea disciplinei              | Tehnici avansate de programare             |
   | Titularul activităților de curs    | Lect. Dr. Marius Apetrii/Drd. Petru Rebeja |
   | Titularul activităților de seminar | Lect. Dr. Marius Apetrii/Drd. Petru Rebeja |
   | An de studiu                       | III                                        |
   | Semestru                           | IV                                         |
   | Regimul disciplinei                | Opțional                                   |
** Evaluare
   :PROPERTIES:
   :CUSTOM_ID: evaluare
   :END:
   | Tip activitate | Criterii de evaluare                                                        | Metode de evaluare                          | Pondere în nota finală |
   |----------------+-----------------------------------------------------------------------------+---------------------------------------------+------------------------|
   | Curs           | Cunoașterea și utilizarea corectă a noțiunilor și rezultatelor fundamentale | 2 teste (S3 şi S9)(*TS*)                    |                    60% |
   | Laborator      | Implementarea corectă a rezultatelor teoretice                              | Evaluarea portofoliului (teme+proiect)(*P*) |                    40% |
   |----------------+-----------------------------------------------------------------------------+---------------------------------------------+------------------------|
*** Standard minim de performanță:
    \begin{equation}
    TS \ge 5
    \end{equation}
    \begin{equation}
    P \ge 5
    \end{equation}

** Referințe bibliografice
   :PROPERTIES:
   :CUSTOM_ID: bibliografie
   :END:
   1. Liviu Negrescu, Lavinia Negrescu, *Limbajul C# pentru începători*, Editura Albastră, 2011
   2. Joseph Albahari, Ben Albahari, *C# 7.0 in a Nutshell: The Definitive Reference*, O'Reilly, 2017
   3. Adam Freeman, *Pro ASP.NET Core MVC*, Apress, 2016
   4. Adam Freeman, *Pro Entity Framework Core 2 for ASP.NET Core MVC*, Apress, 2018
   5. [[https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes][Visual Studio 2019]]
   6. [[https://git-scm.com/][Manual Git Online]]
   7. Robert C. Martin, *Design Principles and Design Patterns*, 2000
   8. Martin Fowler, *Refactoring. Improving the Design of Existing Code*, Addison-Wesley, 2018
   9. [[https://www.martinfowler.com/microservices/][Martin Fowler, Colecția de articole despre microservicii]]
* Date de contact
  :PROPERTIES:
  :CUSTOM_ID: contact
  :END:
** Marius Apetrii
   :PROPERTIES:
   :CUSTOM_ID: marius-apetrii
   :END:
*** Email
   #+begin_src emacs-lisp :exports code
   (concat "mapetrii" "@uaic.ro")
   #+end_src
** Petru Rebeja
   :PROPERTIES:
   :CUSTOM_ID: petru-rebeja
   :END:
*** Email
   #+begin_src emacs-lisp :exports code
   (concat "petru" "." "rebeja" "@gmail.com")
   #+end_src
* Săptămâna 01
  :PROPERTIES:
  :CUSTOM_ID: s01
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s01-curs
   :END:
   *Infrastructură și unelte*

   La curs discutăm despre infrastructura și uneltele necesare pentru dezvoltarea aplicațiilor pe platforma =.net core=.

   Prezentarea de la curs poate fi descărcată în format [[file:s01/curs-s01.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s01-lab
   :END:
   *Pregătirea mediului de lucru*
   - Instalare [[https://visualstudio.microsoft.com/downloads/][Visual Studio 2019 Community Edition]]
   - Cont [[https://github.com/][GitHub]]
   - Cont [[https://dev.azure.com/][Azure DevOps]]
* Săptămâna 02
  :PROPERTIES:
  :CUSTOM_ID: s02
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s02-curs
   :END:
   *Recapitulare și noțiuni de bază*

   La curs discutăm despre tipurile de date în =.net= și exemplificăm principiile programării orientate-obiect pe o mini-aplicație.
   Discuția continuă cu diferența

   Prezentarea de la curs poate fi descărcată în format [[file:s02/curs-s02.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s02-lab
   :END:
   La laborator aplicăm conceptele discutate la curs în dezvoltare unei mini-aplicații.

   O parte din noțiunile discutate se regăsesc și în acest [[https://rebeja.eu/posts/fii-practic-2016/][articol]].
* Săptămâna 03
  :PROPERTIES:
  :CUSTOM_ID: s03
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s03-curs
   :END:
   *Modularizare, =git= și evaluare*

   La curs discutăm despre diferențele dintre clasele abstracte și interfețe, continuăm cu acuplarea și coeziunea și apoi trecem în revistă pașii fluxului de lucru GitHub.

   Prezentarea de la curs poate fi descărcată în format [[file:s03/curs-s03.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s03-lab
   :END:
   La laborator avem prima evaluare din acest semestru.

   Pagina cu cerințele pentru evaluare este pe [[https://github.com/RePierre/tap2021-e01][GitHub]].
* Săptămâna 04
  :PROPERTIES:
  :CUSTOM_ID: s04
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s04-curs
   :END:
   *Gestionarea resurselor și ecosistemul NuGet*

   La curs discutăm despre gestionarea eficientă a resurselor în =.net= și un șablon de implementare pentru =IDisposable=.

   Apoi, discutăm și despre cum este indicat să adăugăm biblioteci din surse terțe la aplicația noastră.

   Prezentarea de la curs poate fi descărcată în format [[file:s04/curs-s04.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s04-lab
   :END:
   La laborator exemplificăm instalare de biblioteci terțe folosind =NuGet= și continuăm dezvoltarea aplicației demonstrative.
* Săptămâna 05
  :PROPERTIES:
  :CUSTOM_ID: s05
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s05-curs
   :END:
   *Principiile =SOLID= și modularizarea codului-sursă*

   La curs enunțăm și exemplificăm principiile =SOLID= și discutăm despre cât este de important să modularizăm codul-sursă.

   Prezentarea de la curs poate fi descărcată în format [[file:s05/curs-s05.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s05-lab
   :END:
   La laborator modularizăm aplicația demonstrativă.
* Săptămâna 06
  :PROPERTIES:
  :CUSTOM_ID: s06
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s05-curs
   :END:
   *Delegates,  Attributes, Lambda Expressionis & Extension Methods*

   La curs discutăm despre Delegates,  Attributes, Lambda Expressionis și Extension Methods.

   Prezentarea de la curs poate fi descărcată în format [[file:s06/curs-s06.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s06-lab
   :END:
   La laborator extindem aplicația demonstrativă și începem să discutăm despre proiectele de curs.
* Săptămâna 07
  :PROPERTIES:
  :CUSTOM_ID: s07
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s07-curs
   :END:
   *LINQ & Entity Framework*

   La curs discutăm despre =LINQ=, =Entity Framework= și cum abstractizăm accesul la date cu =Repository Pattern=.

   Prezentarea de la curs poate fi descărcată în format [[file:s07/curs-s07.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s07-lab
   :END:
   La laborator începem să definim schema de baze de date pentru proiectul de curs.
* Săptămâna 08
  :PROPERTIES:
  :CUSTOM_ID: s08
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s08-curs
   :END:
   *Unit of Work pattern & Dependency Injection*

   La curs discutăm despre cum putem încapsula operațiile asupra bazei de date într-o tranzacție cu =Unit of Work pattern= apoi discutăm despre =Dependency Injection= și cum această tehnică ne ajută să decuplăm codul-sursă și să-i reducem complexitatea.

   Prezentarea de la curs poate fi descărcată în format [[file:s08/curs-s08.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s08-lab
   :END:
   La laborator analizăm propunerile pentru proiectele de curs.
* Săptămâna 09
  :PROPERTIES:
  :CUSTOM_ID: s09
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s09-curs
   :END:
   *Test-Driven Development și Recapitulare*

   La curs discutăm despre =Test-Driven Development= și facem o recapitulare înainte de evaluare.

   Prezentarea la curs poate fi descărcat în format [[file:s09/curs-s09.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s09-lab
   :END:
   La laborator avem a doua evaluare din acest semestru.

   Pagina cu cerințele pentru evaluare este pe [[https://github.com/RePierre/tap2021-e02][GitHub]].
* Săptămâna 10
  :PROPERTIES:
  :CUSTOM_ID: s10
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s10-curs
   :END:
   *Baze de date*

   La curs discutăm despre baze de date, proiectarea și normalizarea acestora, cât și despre bunele practici legate de istoricul evoluției schemei bazelor de date.

   Prezentarea la curs poate fi descărcat în format [[file:s10/curs-s10.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s10-lab
   :END:
   La laborator exemplificăm noțiunile de la curs și începem proiectarea bazei de date pentru proiectul de curs.
* Săptămâna 11
  :PROPERTIES:
  :CUSTOM_ID: s11
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s11-curs
   :END:
   *ASP.NET Core MVC --- Introducere*

   La curs discutăm despre şablonul =Model-View-Controller= şi facem introducerea platformei =ASP.NET Core MVC=.

   Prezentarea la curs poate fi descărcată în format [[file:s11/curs-s11.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s11-lab
   :END:
   Laboratorul din această săptămână nu se ține --- 30 aprilie 2021 este zi liberă cu ocazia sărbătorilor de Paști.
* Săptămâna 12
  :PROPERTIES:
  :CUSTOM_ID: s12
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s12-curs
   :END:
   *=TPL=, =middleware= şi securitatea în ASP.NET Core MVC*

   La curs discutăm despre =Task Parallel Library= şi cum =async= şi =await= ne ajută în implementarea proprie a modulelor care se ocupă de autorizare şi autentificare în =ASP.NET Core MVC=.

   Prezentarea la curs poate fi descărcată în format [[file:s12/curs-s12.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s12-lab
   :END:
   La laborator lucrăm la proiectul de la finalul semestrului.
* Săptămâna 13
  :PROPERTIES:
  :CUSTOM_ID: s13
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s13-curs
   :END:
   *Hackathon P01*

   La curs demarăm un hackathon din patru părți în care reluăm ciclul de dezvoltare a unei aplicații de la zero pe platforma =ASP.Net Core MVC=.

   În prima parte a acestui hackathon vom identifica fluxurile de lucru uzuale pe care aplicația să le acopere precum și obiectele din domeniu și relațiile dintre acestea.

* Legături utile
  :PROPERTIES:
  :CUSTOM_ID: links
  :END:
  - [[https://guides.github.com/introduction/flow/][GitHub flow]] --- o descriere a modului de lucru pe GitHub.
  - [[https://www.linqpad.net/][LINQPad - The .NET Programmer's Playground]] --- aplicație pentru interogarea bazelor de date cu LINQ.
  - [[https://www.databasestar.com/database-normalization/][Database Normalization: A Step-By-Step-Guide With Examples]] --- ghid de normalizare a bazei de date.
  - [[https://refactoring.guru/][Refactoring and Design Patterns]] --- catalog de șabloane de proiectare și tehnici de refactoring.
