#+title: Tehnici Avansate de Programare
#+author: Petru Rebeja
#+description: Pagina cursului Technici Avansate de Programare. Facultatea de Matematică, Universitatea Alexandru Ioan Cuza, Iași.
#+language: ro
#+select_tags: export
#+exclude_tags: noexport
#+options: author:t broken-links:nil c:nil creator:nil
#+options: timestamp:nil title:t toc:t todo:t |:t
#+options: d:(not "LOGBOOK") date:nil e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+setupfile: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup
#+html_mathjax: align: left indent: 5em tagside: left font: Neo-Euler
* Prezentare
  :PROPERTIES:
  :CUSTOM_ID: prezentare
  :END:
  Cursul *Tehnici Avansate de Programare* își propune să faciliteze să ofere pregătirea necesară pentru studenții Facultății de Matematică în vederea urmării unei cariere în domeniul IT.

  Pe parcursul cursului studenții vor acumula un set de bune practici pentru dezvoltarea produselor software pe care le vor aplica lucrând în echipe la dezvoltarea unei aplicații Web.
Aplicația va fi propusă de către membrii echipei.

  Prezentarea cursului este disponibilă și în format [[file:course-presentation.pdf][pdf]].
* Fișa disciplinei
  :PROPERTIES:
  :CUSTOM_ID: fisa-disciplinei
  :END:
** Date despre program
   :PROPERTIES:
   :CUSTOM_ID: date-despre-program
   :END:
   | Instituția de învățământ        | Universitatea „Alexandru Ioan Cuza” din Iași |
   | Facultatea                      | Facultatea de Matematică                     |
   | Departamentul                   | Matematică                                   |
   | Domeniul de studii              | Matematică                                   |
   | Ciclul de studii                | Licență                                      |
   | Programul de studii/Calificarea | Matematică-Informatică                       |
** Date despre disciplină
   :PROPERTIES:
   :CUSTOM_ID: date-despre-disciplina
   :END:
   | Denumirea disciplinei              | Tehnici avansate de programare             |
   | Titularul activităților de curs    | Lect. Dr. Marius Apetrii/Drd. Petru Rebeja |
   | Titularul activităților de seminar | Lect. Dr. Marius Apetrii/Drd. Petru Rebeja |
   | An de studiu                       | III                                        |
   | Semestru                           | IV                                         |
   | Regimul disciplinei                | Opțional                                   |
** Evaluare
   :PROPERTIES:
   :CUSTOM_ID: evaluare
   :END:
   | Tip activitate | Criterii de evaluare                                                        | Metode de evaluare                          | Pondere în nota finală |
   |----------------+-----------------------------------------------------------------------------+---------------------------------------------+------------------------|
   | Curs           | Cunoașterea și utilizarea corectă a noțiunilor și rezultatelor fundamentale | 2 teste (S3 şi S9)(*TS*)                    |                    60% |
   | Laborator      | Implementarea corectă a rezultatelor teoretice                              | Evaluarea portofoliului (teme+proiect)(*P*) |                    40% |
   |----------------+-----------------------------------------------------------------------------+---------------------------------------------+------------------------|
*** Standard minim de performanță:
    \begin{equation}
    TS \ge 5
    \end{equation}
    \begin{equation}
    P \ge 5
    \end{equation}

** Referințe bibliografice
   :PROPERTIES:
   :CUSTOM_ID: bibliografie
   :END:
   1. Liviu Negrescu, Lavinia Negrescu, *Limbajul C# pentru începători*, Editura Albastră, 2011
   2. Joseph Albahari, Ben Albahari, *C# 7.0 in a Nutshell: The Definitive Reference*, O'Reilly, 2017
   3. Adam Freeman, *Pro ASP.NET Core MVC*, Apress, 2016
   4. Adam Freeman, *Pro Entity Framework Core 2 for ASP.NET Core MVC*, Apress, 2018
   5. https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2017-relnotes
   6. https://git-scm.com/
   7. Robert C. Martin, *Design Principles and Design Patterns*, 2000
   8. Martin Fowler, *Refactoring. Improving the Design of Existing Code*, Addison-Wesley, 2018
   9. https://www.martinfowler.com/microservices/
* Date de contact
  :PROPERTIES:
  :CUSTOM_ID: contact
  :END:
** Petru Rebeja
   :PROPERTIES:
   :CUSTOM_ID: petru-rebeja
   :END:
*** Email
   #+begin_src emacs-lisp :exports code
   (concat "petru" "." "rebeja" "@gmail.com")
   #+end_src
*** Twitter
    =@petrurebeja=

    Anunțurile legate de curs/laborator vor fi marcate cu =#TAP2020=.
** Marius Apetrii
   :PROPERTIES:
   :CUSTOM_ID: marius-apetrii
   :END:
*** Email
   #+begin_src emacs-lisp :exports code
   (concat "mapetrii" "@uaic.ro")
   #+end_src
* Săptămâna 01
  :PROPERTIES:
  :CUSTOM_ID: s01
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s01-curs
   :END:
   *Infrastructură și unelte*

   La curs discutăm despre infrastructura și uneltele necesare pentru dezvoltarea aplicațiilor pe platforma =.net core=.

   Prezentarea de la curs poate fi descărcată în format [[file:s01/curs-s01.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s01-lab
   :END:
   *Pregătirea mediului de lucru*
   - Instalare [[https://visualstudio.microsoft.com/downloads/][Visual Studio 2019 Community Edition]]
   - Cont [[https://github.com/][GitHub]]
   - Cont [[https://dev.azure.com/][Azure DevOps]]
* Săptămâna 02
  :PROPERTIES:
  :CUSTOM_ID: s02
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s02-curs
   :END:
   *Recapitulare și noțiuni de bază*

   La curs discutăm despre tipurile de date în =.net= și exemplificăm principiile programării orientate-obiect pe o mini-aplicație.
   Discuția continuă cu diferența dintre clasele abstracte și interfețe iar spre sfârșit discutăm despre acuplare și coeziune.

   Prezentarea de la curs poate fi descărcată în format [[file:s02/curs-s02.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s02-lab
   :END:
   La laborator aplicăm conceptele discutate la curs în dezvoltare unei mini-aplicații.

   Cerințele pentru temă sunt pe [[https://github.com/RePierre/tap2020-t01][pagina dedicată]] temei pe GitHub.

   O parte din noțiunile discutate se regăsesc și în acest [[https://rebeja.eu/posts/fii-practic-2016/][articol]].
* Săptămâna 03
  :PROPERTIES:
  :CUSTOM_ID: s03
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s03-curs
   :END:
   *Gestionarea resurselor și evaluare*

   La curs discutăm despre gestionarea eficientă a resurselor în =.net= și un șablon de implementare pentru =IDisposable=.

   Prezentarea de la curs poate fi descărcată în format [[file:s03/curs-s03.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s03-lab
   :END:
   La laborator avem prima evaluare din acest semestru.

   Pagina cu cerințele pentru evaluare este pe [[https://github.com/RePierre/tap2020-e01][GitHub]].
* Săptămâna 04
  :PROPERTIES:
  :CUSTOM_ID: s04
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s04-curs
   :END:
   *Fluxul de lucru Git și principiile SOLID*

   La curs discutăm despre cum aplicăm fluxul de lucru Git în contextul unui anumit proiect (cu sau fără drepturi de a crea modificări) și enunțăm și exemplificăm principiile SOLID.
   Printre altele, discutăm și despre cum este indicat să adăugăm biblioteci din surse terțe la aplicația noastră.

   Prezentarea la curs poate fi descărcat în format [[file:s04/curs-s04.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s04-lab
   :END:
   La laborator aplicăm conceptele =SOLID= și fluxul de lucru discutate la curs asupra exercițiului de la [[https://github.com/RePierre/tap2020-t01][tema 1]].
* Săptămâna 05
  :PROPERTIES:
  :CUSTOM_ID: s05
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s05-curs
   :END:
   *Modularizarea codului-sursă*

   La curs discutăm despre cât este de important să modularizăm codul-sursă.

   Prezentarea la curs poate fi descărcat în format [[file:s05/curs-s05.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s05-lab
   :END:
   La laborator modularizăm aplicația implementată la [[https://github.com/RePierre/tap2020-t01][tema 1]].
* Săptămâna 06
  :PROPERTIES:
  :CUSTOM_ID: s06
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s05-curs
   :END:
   *Delegates,  Attributes, Lambda Expressionis & Extension Methods*

   La curs discutăm despre Delegates,  Attributes, Lambda Expressionis și Extension Methods.

   Prezentarea la curs poate fi descărcat în format [[file:s06/curs-s06.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s06-lab
   :END:
   La laborator extindem aplicația implementată la [[https://github.com/RePierre/tap2020-t01][tema 1]] și începem să discutăm despre proiectele de curs.
* Săptămâna 07
  :PROPERTIES:
  :CUSTOM_ID: s07
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s07-curs
   :END:
   *LINQ & Entity Framework*

   La curs discutăm despre =LINQ=, =Entity Framework= și cum abstractizăm accesul la date cu =Repository Pattern=.

   Prezentarea la curs poate fi descărcat în format [[file:s07/curs-s07.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s07-lab
   :END:
   La laborator începem să definim schema de baze de date pentru proiectul de curs.
* Săptămâna 08
  :PROPERTIES:
  :CUSTOM_ID: s08
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s08-curs
   :END:
   *Unit of Work pattern, Dependency Injection & Test-Driven Development*

   La curs discutăm despre cum putem încapsula operațiile asupra bazei de date într-o tranzacție cu =Unit of Work pattern= apoi discutăm despre =Dependency Injection= și =Test-Driven Development=.

   Prezentarea la curs poate fi descărcat în format [[file:s08/curs-s08.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s08-lab
   :END:
   La laborator analizăm propunerile pentru proiectele de curs.
* Săptămâna 09
  :PROPERTIES:
  :CUSTOM_ID: s09
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s09-curs
   :END:
   *Baze de date și Gestiunea sarcinilor de lucru*

   La curs discutăm despre cum păstrăm istoricul bazei alături de istoricul codului-sursă și fluxul de lucru pentru dezvoltarea proiectului de curs.

   Prezentarea la curs poate fi descărcat în format [[file:s09/curs-s09.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s09-lab
   :END:
   La laborator avem a doua evaluare din acest semestru.

   Pagina cu cerințele pentru evaluare este pe [[https://github.com/RePierre/tap2020-e02][GitHub]].
* Săptămâna 10
  :PROPERTIES:
  :CUSTOM_ID: s10
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s10-curs
   :END:
   *ASP.NET Core MVC --- Introducere*

   La curs discutăm despre şablonul =Model-View-Controller= şi facem introducerea platformei =ASP.NET Core MVC=.

   Prezentarea la curs poate fi descărcat în format [[file:s10/curs-s10.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s10-lab
   :END:
   La laborator lucrăm la proiectul de la finalul semestrului.
* Săptămâna 11
  :PROPERTIES:
  :CUSTOM_ID: s11
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s11-curs
   :END:
   *=Task Parallel Library= şi securitatea în ASP.NET Core MVC*

   La curs discutăm despre =Task Parallel Library= şi cum =async= şi =await= ne ajută în implementarea proprie a modulelor care se ocupă de autorizare şi autentificare în =ASP.NET Core MVC=.

   Prezentarea la curs poate fi descărcat în format [[file:s11/curs-s11.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s11-lab
   :END:
   La laborator lucrăm la proiectul de la finalul semestrului.
* Săptămâna 12
  :PROPERTIES:
  :CUSTOM_ID: s12
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s12-curs
   :END:
   *Database design & Introducere în DevOps*

   La curs discutăm despre proiectarea bazelor de date şi facem o scurtă introducere în practicile şi nomenclatura =DevOps=.

   Prezentarea la curs poate fi descărcat în format [[file:s12/curs-s12.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s12-lab
   :END:
   La laborator lucrăm la proiectul de la finalul semestrului.
* Săptămâna 13
  :PROPERTIES:
  :CUSTOM_ID: s13
  :END:
** Curs
   :PROPERTIES:
   :CUSTOM_ID: s13-curs
   :END:
   *De la modularizare la arhitectură*

   Începem cursul cu o discuţie asupra unui studiu de caz --- de ce este indicat să adăugăm un =ViewModel= pentru fiecare entitate, apoi discutăm despre arhitectura sistemelor software.
   La sfârșit implementăm o conductă pentru =Continuous Integration=.

   Prezentarea la curs poate fi descărcat în format [[file:s13/curs-s13.pdf][pdf]].
** Laborator
   :PROPERTIES:
   :CUSTOM_ID: s13-lab
   :END:
   La laborator lucrăm la proiectul de la finalul semestrului şi ne pregătim pentru prezentarea proiectelor.
* Legături utile
  :PROPERTIES:
  :CUSTOM_ID: links
  :END:
  - [[https://visualstudio.microsoft.com/dev-essentials/][Visual Studio Dev Essentials]] --- acces gratuit (limitat) la unelte oferite de Microsoft și partenerii săi.
  - [[https://c4model.com/][Modelul C4]] --- modelul C4 pentru vizualizarea arhitecturii aplicațiilor software. O descriere scurtă a modelului este pe [[https://www.infoq.com/articles/C4-architecture-model/][InfoQ]].
  - [[https://guides.github.com/introduction/flow/][GitHub flow]] --- o descriere a modului de lucru pe GitHub.
  - [[https://www.youtube.com/watch?v=aJnFGMclhU8][Git Workflow Strategies]] --- o comparație între =GitHub flow= și =Git workflow=.
  - [[https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet][Markdown Cheatsheet]] --- exemple de formatare folosind sintaxa =markdown=.
  - [[https://help.github.com/en/github/writing-on-github][Writing on GitHub]] --- formatarea textului folosind sintaxa =markdown= specifică GitHub.
  - [[http://www.albahari.com/threading/part5.aspx][Fire de execuţie în C#]] --- articol despre cum trebuie utilizate firele de execuţie în C# şi conceptele din spate.
  - [[http://www.albahari.com/threading/part5.aspx][Parallel Programming in C#]] --- descriere detaliată a conceptelor din =Task Parallel Library=.
  - [[https://www.linqpad.net/][LINQPad]] --- aplicaţie care permite executarea interogărilor =LINQ= în mod interactiv.
